#!/bin/sh
#
# Returns the Salesforce API version listed in the project definition

[ -f sfdx-project.json ] || { echo "Must be run from the root of an SFDX project" >&2 && exit 1; }
jq .sourceApiVersion sfdx-project.json | sed 's/"//g'
