#!/bin/sh
#
# Run Jest on a set of lightning web components
# Arguments:
#       the set of filepaths or directories to check
#       (optional) "directories"/"files"/"all" indicating if the first argument are directories to search, or filepaths containing files to check, or whether all tests should run
#
# If passed a set of directories, all tests found within those directories will be run. If passed a set of files, any file passed corresponding to an lwc component will cause all of those components' test to run, if any.

[ -n "$1" ] || exit 0
mode="all"
[ -n "$2" ] && mode="$2"

env printf "\e[1;34m-----\n\u279C Running Jest tests\n-----\e[0m\n"

if [ "$mode" = "directories" ]; then
    roots=$(echo "$1" | sed 's| |\n|g')
elif [ "$mode" = "files" ]; then
    roots=$(echo "$1" | grep "/lwc/" | sed 's|/lwc/\([^/]*\).*|/lwc/\1|' | uniq)
elif [ "$mode" = "all" ]; then
    roots=.
fi

[ -n "$roots" ] || { env printf "\e[1;32m\u2713\e[0m No Jest tests to run\n" && exit 0; }

echo "$roots" | xargs npm run test:unit:coverage -- --skipApiVersionCheck -- --passWithNoTests --roots || {
    env printf "\n\e[1;31m\xE2\x9D\x8C Some Jest tests failed, or coverage is insufficient\e[0m\n" >&2
    env printf "\e[1;33m\u2BC5\e[0m Check on failed tests, or missing coverage error messages above\n"
    exit 1
}
